### ISSUE TITLE
Local bibliography is not checked for highlighting missing citations

### ISSUE THREAD

**Issue by vikasrawal** [jkitchin/org-ref-cite#12]
It seems a local bibliography defined using #+bibliography: is not checked and the citation is highlighted as missing if it is not in the global bibliography.

**Comment by jkitchin** [comment]
hm.  I am not able to reproduce that. The fontification is done here by `org-cite-basic-activate`, and it basically is checking to see if a key is a member of what is returned by `org-cite-basic--all-keys`.

The first thing to check is the output of 
```
#+BEGIN_SRC emacs-lisp
(org-cite-list-bibliography-files)
#+END_SRC
``` 

in that file to see if it lists the correct bibliography.
