### ISSUE TITLE
Spurious semi-colon when shifting references within a citation

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref-cite#13]
If I insert this citation:

```console
[cite:@kaye2017;@amin2008;@kohn2001]
```

... and then shift any citation, I end up with a spurious semi-colon at the end.

```console
[cite:@kaye2017;@kohn2001;@amin2008;]
```
Though, I guess this relates to earlier discussion about global vs local affixes, and isn't technically wrong.

**Comment by jkitchin** [comment]
I don't think it is spurious. It is how `org-element-interpret-data` sees a citation:

```
#+BEGIN_SRC emacs-lisp
(org-element-interpret-data `(citation-reference (:key "test")))
#+END_SRC

#+RESULTS:
: @test;
```

**Comment by bdarcus** [comment]
OK no problem.
