### ISSUE TITLE
Add annotation to `org-ref-cite-follow` completing-read

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref-cite#14]
I'm still not sure the best UI here (see https://github.com/bdarcus/bibtex-actions/issues/203), but assuming the current behavior here is, add a preview annotation to the list of keys to select from?

https://github.com/jkitchin/org-ref-cite/blob/c1347c48a20134c3aa498297719c0a4e9a340671/org-ref-cite-follow.el#L298

Also, I would _maybe_ change the prompt to "Citation key " or (org-cite language) "Citation reference"?

**Comment by jkitchin** [comment]
I added the annotation, and they show up, but you can't use them to select anything. That doesn't seem super useful to me.

regarding the UI, I think I see what you are going for, which is to differentiate following a reference from following a citation, where your follow action would be used on each reference in the citation. A solution could be different hydra menus on the cite part vs the references. Maybe one could write functions that work on a key or list of keys where it makes sense. I haven't had any need for that in my own work, usually I act on citations one at a time.
