### ISSUE TITLE
Installing org-ref-cite `Error (use-package): Cannot load org-ref-cite`.

### ISSUE THREAD

**Issue by ebouna** [jkitchin/org-ref-cite#15]
I'd like to try out org-ref-cite which I find very interesting (apart from the package bibtex-actions). So I cloned the git repository, copied the set up to my init and adjusted the paths. In addition, I installed the packages org-ref-cite depends on. Unfortunately, I still get the message `Error (use-package): Cannot load org-ref-cite`. Is it possible to have org-ref-cite alone without the rest of scimax? Or is maybe some kind of installation of org-ref-cite needed I am not aware of? Thanks a lot of your help in advance.

**Comment by bdarcus** [comment]
This doesn't have any dependency on scimax. FWIW, here's the recipe I use to install it in Doom (which uses straight recipe format), for use with `bibtex-actions`.

```elisp
(package! org-ref-cite :recipe
  (:host github
   :repo "jkitchin/org-ref-cite"
   ;; exclude the main file with package-requires line, since we don't
   ;; need it, and don't want it forcing installation of ivy, etc.
   :files ("*.el" (:exclude "org-ref-cite.el"))) :pin "c1347c48a20134c3aa498297719c0a4e9a340671")
```

**Comment by jkitchin** [comment]
I am fairly sure this means you have not setup the load-path correctly. Without seeing what you are using for the init file though, and without knowing where you cloned the repo, I don't know how to help you further.

**Comment by ebouna** [comment]
Thank you very much to both of  you! I took into account both of your answers. That meant, I also checked my load-path once again several times. In the end, I found an error I had missed so far. Now  `org-ref-cite` is properly loaded. But there are still some issues I could not solve until now. Thus, when I call "Style", Style is not highlighted in yellow as in your video and no list of options is displayed:
![grafik](https://user-images.githubusercontent.com/82314717/128780463-86468506-09c3-48eb-b21b-ec078ef80b60.png)
Similarly, "BibTeX entries:" is not highlighted in yellow even though it is followed by a list of entries. I suppose this is an issue that has to do with ivy-bibtex, but I was not able to figure out a solution. Maybe you have an idea? 
As far as I can see, I installed all required packages. ivy-bibtex was installed from MELPA, so no further configuration seems to be necessary.
By the way, this is my configuration, which is in principle the same as in the readme, apart from the file paths: 
```
;;======Org-ref-cite===========

(use-package ivy-bibtex
  :init
  (setq bibtex-completion-bibliography '("~/elisp/org-ref-cite/org-ref-cite.bib")
	bibtex-completion-notes-path "~/elisp/org-ref-cite/notes"
	bibtex-completion-notes-template-multiple-files "#+TITLE: Notes on: ${author-or-editor} (${year}): ${title}\n\nSee [cite/t:@${=key=}]\n"
	bibtex-completion-library-path '("~/elisp/org-ref-cite/bibtex-pdfs/")
	bibtex-completion-additional-search-fields '(keywords)
	bibtex-completion-display-formats
	'((article       . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${journal:40}")
	  (inbook        . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
	  (incollection  . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
	  (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
	  (t             . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*}"))
	bibtex-completion-pdf-open-function
	(lambda (fpath)
	  (call-process "open" nil 0 nil fpath))))

(use-package citeproc)

(use-package org-cite
  :load-path "~/elisp/org-mode/lisp"
  :config
  (require 'oc-csl))

(add-to-list 'load-path "~/elisp/org-ref-cite/")


(use-package org-ref-cite
  :load-path "~/elisp/org-ref-cite/"
  :config
  ;; I like green links
  (set-face-attribute 'org-cite nil :foreground "DarkSeaGreen4")
  (set-face-attribute 'org-cite-key nil :foreground "forest green")
  (setq
   org-cite-global-bibliography bibtex-completion-bibliography
   ;; https://github.com/citation-style-language/styles
   ;; or https://www.zotero.org/styles
   org-cite-csl-styles-dir "~/elisp/org-ref-cite/csl-styles"
   org-cite-insert-processor 'org-ref-cite
   org-cite-follow-processor 'org-ref-cite
   org-cite-activate-processor 'org-ref-cite
   org-cite-export-processors '((html csl "chicago-author-date-16th-edition.csl")
			        (latex org-ref-cite)
			        (t basic)))

  (define-key org-mode-map (kbd "C-c \\") 'org-cite-insert))

(setq  flyspell-duplicate-distance 0
       flyspell-mark-duplications-flag nil
       warning-minimum-level :error)


```

**Comment by jkitchin** [comment]
What you describe looks like what you see if you don't have ivy-mode enabled. If you press tab with what you see, do you get some candidates? If so, then it is certainly because ivy-mode is not enabled.

**Comment by ebouna** [comment]
Thanks a lot. This seems to have solved the ivy-problem.
