### ISSUE TITLE
Two or more citations with page references following one after another

### ISSUE THREAD

**Issue by ebouna** [jkitchin/org-ref-cite#17]
I'm aware of limitations with regard to the simultaneous use of prefixes and suffixes in Org-ref-cite and I'd like to know if a combination like the following is not possible in Org-ref-cite: 
![grafik](https://user-images.githubusercontent.com/82314717/129002636-7daf3083-a21f-4826-90c0-340893751523.png)

In other words, using Org-ref-cite, how can I create two or more citations, each with a page reference, following one after another? I'm asking this because this is a citation case that is of course not uncommon in scientific papers. On the other hand, my Org-ref-cite version, unfortunately, considers it erroneous, cf. the suffix highlighted in red on the screenshot. 
Thanks for your help in advance.

**Comment by denismaier** [comment]
The reason for this is that org-cite is natbib-centric so it will flag those (because natbib does not support those).
These things are all legal according to the org-cite syntax, and they do work with other exporters, e.g. biblatex, csl. Just to remember: exporting and fontification are two different things.

**Comment by ebouna** [comment]
Thanks, @denismaier.
I've just realized that in your last video on Org-ref-cite, @jkitchin, you hint at the fact that the problem described above comes from natbib and that biblatex allows one to have suffixes in the middle. 
I've now included biblatex as a processor like so:
```
(use-package org-cite
  :load-path "~/elisp/org-mode/lisp"
  :config
  (require 'oc-biblatex))
```
However, now `cite/t:@kitchin-2018` with the t-prefix is processed in the classical way rendered as "Kitchin (2018)", as originally defined in the org-cite syntax, and "(Kitchin 2018)" has to be coded as `[cite:@kitchin-2018]`, i.e. with mere `cite`. You tried to avoid the latter in Org-ref-cite by introducing `cite/t` as a default. You mention in your third video that mere `cite` would cause some kind of problems related to Org-ref, but you did not elaborate on this. 

Do you think it may still be possible/ safe to use citations of the type `[cite:@kitchin-2018]` in Org-cite-ref when using biblatex as a processor?

**Comment by denismaier** [comment]
By the way, if you want to stick to the `cite/t:` default, you can also mess around with this function from oc-biblatex.el:

```elisp
(defun org-cite-biblatex-export-citation (citation style _ info)
  "Export CITATION object.
STYLE is the citation style, as a string or nil.  INFO is the export state, as
a property list."
  (apply
   #'org-cite-biblatex--command citation info
   (pcase style
     ;; "author" style.
     (`(,(or "author" "a") . ,(or "caps" "c"))         '("Citeauthor*"))
     (`(,(or "author" "a") . ,(or "full" "f"))         '("citeauthor"))
     (`(,(or "author" "a") . ,(or "caps-full" "cf"))   '("Citeauthor"))
     (`(,(or "author" "a") . ,_)                       '("citeauthor*"))
     ;; "locators" style.
     (`(,(or "locators" "l") . ,(or "bare" "b"))       '("notecite"))
     (`(,(or "locators" "l") . ,(or "caps" "c"))       '("Pnotecite"))
     (`(,(or "locators" "l") . ,(or "bare-caps" "bc")) '("Notecite"))
     (`(,(or "locators" "l") . ,_)                     '("pnotecite"))
     ;; "noauthor" style.
     (`(,(or "noauthor" "na") . ,_)                    '("autocite*"))
     ;; "nocite" style.
     (`(,(or "nocite" "n") . ,_)                       '("nocite" nil t))
     ;; "text" style.
     (`(,(or "text" "t") . ,(or "caps" "c"))           '("Textcite" t))
     (`(,(or "text" "t") . ,_)                         '("textcite" t))
     ;; Default "nil" style.
     (`(,_ . ,(or "bare" "b"))                         '("cite" t))
     (`(,_ . ,(or "caps" "c"))                         '("Autocite" t))
     (`(,_ . ,(or "bare-caps" "bc"))                   '("Cite" t))
     (`(,_ . ,_)                                       '("autocite" t))
     ;; This should not happen.
     (_ (error "Invalid style: %S" style)))))
```

**Comment by ebouna** [comment]
Thanks for this hint.

**Comment by jkitchin** [comment]
> I'm aware of limitations with regard to the simultaneous use of prefixes and suffixes in Org-ref-cite and I'd like to know if a combination like the following is not possible in Org-ref-cite:
> ![grafik](https://user-images.githubusercontent.com/82314717/129002636-7daf3083-a21f-4826-90c0-340893751523.png)
> 
> In other words, using Org-ref-cite, how can I create two or more citations, each with a page reference, following one after another? I'm asking this because this is a citation case that is of course not uncommon in scientific papers. On the other hand, my Org-ref-cite version, unfortunately, considers it erroneous, cf. the suffix highlighted in red on the screenshot.
> Thanks for your help in advance.

As others here have noted, you see this fontification because it is telling you that it will be ignored with the org-ref-cite export processor because natbib does not support it. You have some options.

1. That fontification is done in `org-ref-cite-activate-prefix-suffix`. I think if you have setup an export processor that is not org-ref-cite or natbib, you should not see this fontifcation.
2. Customize the `org-ref-cite-activation-functions` variable and remove `org-ref-cite-activate-prefix-suffix` from it. Then you won't see the fontification.

**Comment by jkitchin** [comment]
> Thanks, @denismaier.
> I've just realized that in your last video on Org-ref-cite, @jkitchin, you hint at the fact that the problem described above comes from natbib and that biblatex allows one to have suffixes in the middle.
> I've now included biblatex as a processor like so:
> 
> ```
> (use-package org-cite
>   :load-path "~/elisp/org-mode/lisp"
>   :config
>   (require 'oc-biblatex))
> ```
> 
> However, now `cite/t:@kitchin-2018` with the t-prefix is processed in the classical way rendered as "Kitchin (2018)", as originally defined in the org-cite syntax, and "(Kitchin 2018)" has to be coded as `[cite:@kitchin-2018]`, i.e. with mere `cite`. You tried to avoid the latter in Org-ref-cite by introducing `cite/t` as a default. You mention in your third video that mere `cite` would cause some kind of problems related to Org-ref, but you did not elaborate on this.
> 
> Do you think it may still be possible/ safe to use citations of the type `[cite:@kitchin-2018]` in Org-cite-ref when using biblatex as a processor?

It is probably fine to use `[cite:@kitchin-2018]`. I have only intermittently seen some behavior where it looks like org-ref thinks that is a cite link. It hasn't caused any obvious problems for me yet though.

**Comment by ebouna** [comment]
> As others here have noted, you see this fontification because it is telling you that it will be ignored with the org-ref-cite export processor because natbib does not support it. You have some options.
> 
>     1. That fontification is done in `org-ref-cite-activate-prefix-suffix`. I think if you have setup an export processor that is not org-ref-cite or natbib, you should not see this fontifcation.
> 
>     2. Customize the `org-ref-cite-activation-functions` variable and remove `org-ref-cite-activate-prefix-suffix` from it. Then you won't see the fontification.

Thanks, I have set up biblatex and csl. With both, the suffixes in the middle weren't marked any more in red, but appeared also in green.

**Comment by ebouna** [comment]
> It is probably fine to use `[cite:@kitchin-2018]`. I have only intermittently seen some behavior where it looks like org-ref thinks that is a cite link. It hasn't caused any obvious problems for me yet though.

That's very good. I have realized that with biblatex as the processor for export, `cite:` and `cite/t:` directly got their original meaning back as defined in org-cite syntax, i.e. as equivalents of autocite vs. textcite. 
Could you give me a hint how I could get this original "behaviour" back for  `cite:` and `cite/t:`, with csl being set as the export processor? Otherwise it seems with csl as the export processor one cannot insert a citation that will be rendered as "Kitchin (2018)". Once again thanks for your help in advance.
