### ISSUE TITLE
How are prefix/suffixes supposed to work with multiple citations?

### ISSUE THREAD

**Issue by jkitchin** [jkitchin/org-ref-cite#2]
I gather that `[cite:prefix @key suffix]` should export to `\cite[prefix][suffix]{key}`.

The following is legal syntax:

`[cite:prefix1 @key1 suffix1; pre2 @key2 suffix2]`

What is this expected to export to (to LaTeX using natbib, with bibtex (not biblatex) as the citation processor)?

Similarly, if you were to shift key2 to come first, what is the expected new citation?

Is it `[cite: pre2 @key2 suffix2, prefix1 @key1 suffix1]`

or should it be  `[cite: pre1 @key2 suffix2, prefix1 @key1 suffix2]` (i.e. preserving the original prefix and suffix)? 

@bdarcus What do you think? Are these supported differently in other backends?

**Comment by bdarcus** [comment]
> I gather that [cite:prefix @key suffix] should export to \cite[prefix][suffix]{key}.

Yes.

> What do you think? Are these supported differently in other backends?

The org-cite model on this is basically biblatex; so there should be a one-to-one mapping.

I don't know how @andras-simonyi is planning to handle it in oc-csl/citeproc, or how it works now (I haven't tested global vs local affixes yet with it), but I'd expect it'd be easy for him as well.

Natbib is a different story though; it's much less expressive on this point.

Nicolas and I discussed the issue a bit on the list. Read this and the subsequent back-and-forth between he and I, where he explains his thinking in oc-natbib:

https://lists.gnu.org/archive/html/emacs-orgmode/2021-05/msg00614.html

I think you'll have to make a similar decision on what you throw away, and how you document this so natbib users know what to expect, and how they should enter their data.  

Maybe you can (possibly optionally?) provide fontification or other "activate" behavior to help your users avoid surprises?

**Comment by jkitchin** [comment]
Those are nice ideas. 

![image](https://user-images.githubusercontent.com/1610070/127208381-0d1a120f-67fe-4d1f-8f8d-173409ae1b22.png)

That exports as: \citep[this prefix is good][this suffix is good]{kitchin-2018-machin-learn-catal,rose-2019-pybliom}

**Comment by bdarcus** [comment]
Looks promising.

Maybe red is too aggressive, but put that in the category of bike-shedding.

Also, thinking about it more, I'd suggest you have a defcustom for this, with it off by default.

And/or ... write some code so it's smart; that it is on when using your export processor or oc-natbib, but off for others that have the richer affix model.

As I've suggested before, I do expect people, including possibly me, to use your activate processor outside of natbib.

On bike-shedding, you could offer faces for a lot of this, so users (and maybe theme developers at some point) can configure the visuals, but you provide sensible defaults?

**Comment by jkitchin** [comment]
I think this is customizable enough to address the issues raised above.
