### ISSUE TITLE
Re-using setup fails for org-cite not found

### ISSUE THREAD

**Issue by ghost** [jkitchin/org-ref-cite#20]
I am trying to use your setup of `org-cite` and `org-ref-cite` but I keep getting the error 
> Cannot open load file: No such file or directory, org-cite.

My adjusted setup is:

```
(add-to-list 'load-path "/Users/XXX/github/org-mode/lisp/")

(use-package org-cite
  :load-path "/Users/XXX/github/org-mode/lisp/"
  :config
 (require 'oc-csl)
  )
```

The folder `org-mode` is the git-repo from https://code.orgmode.org/bzg/org-mode 

Using Emacs 27.2 and `use-package` is also installed.

I cannot find any difference to your setup. Any guidance would be appreciated. Thank you.

**Comment by jkitchin** [comment]
I guess the problem is at https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc.el#L1586, it does not provide org-cite, it just provides oc. In the version I have, it provides both. so maybe you have to change org-cite to oc. It looks like that has been changed since I wrote this code. I have updated this in the readme.

**Comment by ghost** [comment]
Thanks for getting back to me (sorry for bothering with this).

I changed to `oc`, now I get `set-face-attribute: Invalid face: org-cite`

**Comment by jkitchin** [comment]
I don't know about that one, that face should be defined in https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-faces.el#L171.

**Comment by ghost** [comment]
Ok, thanks for pointing out. I keep digging.

**Comment by jkitchin** [comment]
If you use something like:

```
(use-package oc
  :load-path "/Users/jkitchin/Dropbox/emacs/tests/org-mode-git/lisp"
  :config
  (require 'oc-csl))
```

does it work?

**Comment by ghost** [comment]
Unfortunately not.
I get
> error: Invalid face, org-cite

with 

```
(use-package oc
  :load-path  "/Users/lukascbossert/github/org-mode/lisp/"
  :config
  (require 'oc-csl))
```

**Comment by jkitchin** [comment]
have you already put something like (use-package org :load-path  "/Users/lukascbossert/github/org-mode/lisp/") before that?

**Comment by ghost** [comment]
Is it sufficient *just* to have the `org-mode`-repo stored somewhere or do I have to "run"/"install" the repo with its `make`?

**Comment by jkitchin** [comment]
hm. I don't remember what I did. lately, I have just been running `git pull` to update it. I don't see any .elc files in my repo, so I am not sure I ever ran make in it.

**Comment by ghost** [comment]
I am loading 

```
(use-package org
  :ensure nil
  :defer t
  :bind (("C-c l" . org-store-link)
         ("C-c a" . org-agenda)
         ("C-c c" . org-capture)
         (:map org-mode-map (("C-c C-p" . eaf-org-export-to-pdf-and-open)
                             ("C-c ;" . nil))))
  :custom
....
```

before the "experimental" org-ref-cite etc. 

org-version is 9.4.4. with the path to the mentioned path above...

**Comment by jkitchin** [comment]
something doesn't seem right there. I get this from (org-version)

Org mode version 9.4.6 (release_9.4.6-598-g604bfd.dirty @ /Users/jkitchin/Dropbox/emacs/tests/org-mode-git/lisp/)

I think you are using an old org package there, and not the git one. You need to use a :load-path there too.

**Comment by ghost** [comment]
yes! Finally! Great! Thank you!

That was the cause:

```
(use-package org
  :load-path  "/Users/lukascbossert/github/org-mode/lisp/"
  :ensure nil
  :defer t

.
.
.
```

works now.

**Comment by ghost** [comment]
The problem and the solution is also discussed on stackoverflow: https://emacs.stackexchange.com/questions/68127/locally-stored-package-not-found/68132
