### ISSUE TITLE
Best tool for bibliographic management?

### ISSUE THREAD

**Issue by vikasrawal** [jkitchin/org-ref-cite#21]
My apologies if I have missed something obvious. I was wondering if org-ref/org-ref-cite have any tool build in for adding bibliographic entries manually to the bibtex database. How do you do it? That is, if I need to manually insert a reference in the bibtex database while working on an org file, does org-ref-cite provide me some key bindings that would open something like ebib?

**Comment by jkitchin** [comment]
org-ref has many ways of adding bibliographic entries, but org-ref-cite (this repo) doesn't.

org-ref-cite can open a key to the bibtex file. It doesn't have anything connected to ebib. Others have made follow processors for something like that on the mailing list I think.
