### ISSUE TITLE
Citation cannot be inserted as 1st item in a footnote

### ISSUE THREAD

**Issue by ebouna** [jkitchin/org-ref-cite#23]
When I try to insert a citation as the first item into a non-inline-definition  footnote, org-ref-cite refuses to insert the citation returning in the minibuffer "Cannot insert citation here". The same problem does not occur if the footnote has an inline definition. As for non-inline-definition footnotes, if I copy the citation into the footnote, no problem occurs, either. The citation is also properly exported to LaTeX. Thanks for your help!

**Comment by jkitchin** [comment]
I think this is an issue to be solved in org-mode, not in this package.
