### ISSUE TITLE
Citation cannot be inserted as 1st item in plain list

### ISSUE THREAD

**Issue by ebouna** [jkitchin/org-ref-cite#24]
Dear John,
I have just realized that org-ref-cite does not allow one to insert a citation as a 1st item in a plain list, neither. On the other hand, it is nonetheless possible to copy and paste a citation to this position. This problem seems to be related to the previous issue I have raised (org-ref-cite not inserting citations as 1st item in footnotes). Unfortunately, I have not got a reaction to that preceding issue so far, although you have always been replied to any of my questions very quickly. So I hope this repo is still active.
Best regards,
Elias

**Comment by jkitchin** [comment]
I believe this is a limitation in org-cite, not in org-ref-cite. Probably it is in `org-cite--insert-string-*` functions.  This is a design feature that the org-developers put in to prevent citations in places that it would cause problems. I think they do that to aggressively, and as you point out one can always copy/paste or type them in.

This repo is not currently active for me. I have made the original org-ref compatible with all the features the new syntax enables (full pre/post note support, export with csl, etc). I will probably stay with the old link syntax, which also fully supports cross-references, and other features I find important in my work.

**Comment by hrdl-github** [comment]
I use a modified version of `org-cite--allowed-p` in `lisp/oc.el` in `org-mode`, replacing
```
;; Paragraphs and blank lines at top of document are fine.
((memq type '(nil paragraph)))
```
with
```
;; Paragraphs, blank lines at top of document, and items are fine.
((memq type '(nil paragraph item)))
```

**Comment by jkitchin** [comment]
I think that is fine for a personal solution. I wouldn't do it in this package though; I think this package should remain consistent with what org intends, and org issues should be fixed in org.

I would implement it personally as an around advice, rather than modifying the lisp/oc.el code.

**Comment by ebouna** [comment]
Thanks a lot, lennonhill, for this solution you suggested. This is great.
Having at least a personal solution that works for me is absolutely fine.

Am Mittwoch, 29. September 2021 schrieb lennonhill ***@***.***

**Comment by ebouna** [comment]
Thanks also for this explanation. I absolutely understand the reason for
not fixing things that should be fixed in org. Anyway, it is good to have
personal solution.

Am Donnerstag, 30. September 2021 schrieb John Kitchin <
***@***.***>:

**Comment by jkitchin** [comment]
I agree, and that is exactly what I would do for my own solution!
