### ISSUE TITLE
lazy load some features

### ISSUE THREAD

**Issue by tshu-w** [jkitchin/org-ref-cite#26]
Hi, thank you for such an awesome package, can't wait for it going on MELPA. Though org 9.5 has been released, it can be considered 😄

After a brief try, I have a suggestion if we can speed up `(require 'org-ref-cite)` by lazy loading. While I know I could just require parts of it, I think lazy loading features would make it easier for newbies to use.

For example:
1. we shouldn't `(require 'org-ref)` if the user didn't need it. `(benchmark-run (require 'org-ref-cite-compat)) ;; (2.06666 0 0.0)`
2. `ivy-set-display-transformer` and other non-defined settings

**Comment by jkitchin** [comment]
Thanks for the suggestion. I moved the require inside the function, which should make it not load unless you call the function.
