### ISSUE TITLE
Alternate actions menu that matches org-cite-follow?

### ISSUE THREAD

**Issue by blester125** [jkitchin/org-ref-cite#27]
Sorry for the noob question, but I'm a little shaky when it comes to different parts of ivy.

Is it possible for the menu that is created when your open the alternative actions to match the one that happens when you click on the link (the follow action)? That menu looks really nice an having consistent keybindings is nice (for example, edit notes is `e` in the alternate options for insert but is `n` when using follow).

I guess the main disconnect is that I often am using the insert action as a menu to interact with my bibliography without having to insert the link first, not sure if there is a better way I should be handling that use case.

**Comment by jkitchin** [comment]
I don't think that is possible, at least as far as looks go. When you click on the link you get a hydra menu, but when you look at an alternative action, it is done in ivy.

You can set the shortcuts in `org-ref-cite-alternate-insert-actions` to anything you want. I pushed a change to make this one n, I guess that makes sense for consistency (although it probably differs from ivy-bibtex now that I think about it).

You could try using ivy-bibtex with its actions if all you are doing is trying to do something in the bib file. What you are doing is basically equivalent to that though.

**Comment by blester125** [comment]
> When you click on the link you get a hydra menu, but when you look at an alternative action, it is done in ivy.

That was basically my main question, thank you!
