### ISSUE TITLE
Align hydra columns

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref-cite#3]
I tried to figure out how to fix this, but couldn't.

![Screenshot from 2021-07-27 01-06-45](https://user-images.githubusercontent.com/1134/127098905-b23deade-0cc4-4de6-b0ba-588e76b326c6.png)

Interestingly, standard `hydra` has the `:columns` parameter, which looks like it should format columns correctly. But `pretty-hydra` doesn't appear to support it .

If you could remove the colon,  as in `transient`, then adding the preceding space would align it all,

**Comment by jkitchin** [comment]
I think this is solved with the new hydra rewrite:

![image](https://user-images.githubusercontent.com/1610070/127208249-93685463-e0f7-4dc1-b382-6adb809e14b8.png)

It isn't quite as pretty as before, but still nice.
