### ISSUE TITLE
Extension point for hydra

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref-cite#4]
I was reviewing the `org-roam-bibtex` code to see what would be involved in adapting it for `org-cite`.

https://github.com/org-roam/org-roam-bibtex/pull/201

It has a hydra now, with extension points to add additional actions. See this, and the following two functions.

https://github.com/org-roam/org-roam-bibtex/blob/13de4262d87debdbc43f8e2bd72b991b7284e705/org-roam-bibtex.el#L312

So my question: is there a way it would be possible to offer an extension point on the hydra here, such that one could add ORB-related actions?

My follow processor is `embark-act` based. so all that would be involved is registering a keymap.

**Comment by jkitchin** [comment]
I rewrote the hydra code which should address this. You can use `defhydra+' to extend a hydra.
