### ISSUE TITLE
Activate customization

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref-cite#7]
This is a followup to:

- Question: " https://github.com/jkitchin/org-ref/issues/885#issuecomment-884977097
- Answer: https://github.com/jkitchin/org-ref/issues/885#issuecomment-885260325

In the latter, @jkitchin says:

> I don't see why you couldn't require that lib, and add (org-cite-csl-activate citation) into an activate function. I already sort of do that in oc-bibtex.el, I call (org-cite-basic-activate citation) and then add some extra properties.

So [this](https://github.com/jkitchin/org-ref-cite/blob/a2cb37eeafab110fc8471be9283056a707948a38/org-ref-cite-activate.el#L77) is the line in question:

``` elisp
(defun org-ref-cite-activate (citation)
  "Add a keymap to cites.
Argument CITATION is an org-element holding the references."
  (org-cite-basic-activate citation)
```

So you're just using `oc-basic for fontification?

As in, that line could be changed to use `org-cite-csl-activate` instead?

If yes, could you add a variable so we can just set that with `setq`?

And on the flip side, perhaps @andras-simonyi could do something similar on his end to import your functionality?

Or are you saying we should write our own active processor that imports logic from these two activate processors?

What do you two think?

**Comment by jkitchin** [comment]
My activate processor starts with `(org-cite-basic-activate citation)` and then adds these things to it:

1. adds a keymap and a different tooltip that shows how it exports with org-ref-cite
2. adds fontification of prefix/suffix that is ignored by the exporter
3. adds fontification of unsupported sytles.

You could certainly use `org-cite-csl-activate` instead if you wanted to. 

I think you are making a bigger deal here than necessary. You can make an activation function like this

```
(org-cite-register-processor 'my-activator
  :activate  (lamba (citation)
		    (activate-func1 citation)
		    (activate func2 citation) ...))
```
I refactored my activate processor like this. You can customize `org-ref-cite-activation-functions` if you want a different behavior.

So, if you don't like some feature or want to change it, you can just `(setq org-ref-cite-activation-functions '(your list of functions)` and they don't even have to be from org-ref-cite.

**Comment by bdarcus** [comment]
> I think you are making a bigger deal here than necessary.

Probably because I haven't really touched activate functionality :-)

So the example is helpful!
